---
- name: windows play
  hosts: windows

  tasks:
    - name: create a directory
      win_file:
        path: C:\Users\Administrator\Desktop\test_dir
        state: directory
    - name: download file from online
      win_get_url:
        url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz
        dest: C:\Users\Administrator\Desktop\test_dir

    - name: Update all package
      win_updates:
        category_names: '*'
        reboot: true